apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: suxess-it-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/charts
    targetRevision: HEAD
    path: grafana
  destination:
    namespace: suxess-it-grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
