apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-k8sgpt
  namespace: suxess-it-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/charts
    targetRevision: main
    path: k8sgpt
  destination:
    server: https://kubernetes.default.svc
    namespace: suxess-it-k8sgpt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true