apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: suxess-it-admin
spec:
  destination:
    name: ''
    namespace: suxess-it-kyverno
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kyverno.github.io/kyverno/'
    targetRevision: 3.0.4
    chart: kyverno
    helm:
      values: |
        admissionController.replicas: 3
        backgroundController.replicas: 2
        cleanupController.replicas: 2
        reportsController.replicas: 2
        admissionController.container.securityContext: null
        admissionController.initContainer.securityContext: null
        config:
          webhooks:
            - namespaceSelector:
                matchExpressions:
                        - key: kubernetes.io/metadata.name
                          operator: NotIn
                          values:
                            - suxess-it-kyverno
                        - key: openshift.io/run-level
                          operator: NotIn
                          values:
                            - "0"
                            - "1"
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
