apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sx-kyverno
  namespace: suxess-it-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/suxess-it/charts
    targetRevision: main
    path: kyverno
  destination:
    namespace: suxess-it-kyverno
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
