apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-demo-dev
  namespace: suxess-it-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/jkleinlercher/gitops-monitor-demo
    targetRevision: main
  destination:
    namespace: suxess-it-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true