apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: suxess-it-admin
spec:
  project: default
  source:
    repoURL: 'https://aquasecurity.github.io/helm-charts/'
    targetRevision: 0.15.1
    chart: trivy-operator
    helm:
      values: |
        operator:
          metricsVulnIdEnabled: true
        serviceMonitor:
          enabled: true
        trivyOperator:
          reportResourceLabels: "backstage.io/kubernetes-id"
        trivy:
          ignoreUnfixed: true
          timeout: "10m0s"
        targetNamespaces: "suxess-it-dev"
  destination:
    namespace: suxess-it-trivy
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
